web:
  build: .
  command: npm start
  volumes:
    - ./:/app
  ports:
    - "8000:8000"
  links:
    - mongo
  environment:
    PORT: 3000
    NODE_ENV: production
mongo:
  image: mongo
  ports:
    - "27017:27017"

# Uncomment this block to populate app data.
#mongo-seed:
#  build: ./mongo-seed
#  links:
#    - mongo